package com.logica.ngph.persistence.entities;

import java.sql.Timestamp;



/**
 * 
 * @author mohdabdulaa
 *
 */
public class NgphCanonical
{
	//The unique reference for every payment - generated by NGPH
	//@Column MSGS_MSGREF
	private String msgRef;
	
	//The message of group header if this payment is part of a bulk message
	//@Column MSGS_GRP_MSGID
	private String grpMsgId;
	
	//The sequence of this message in the group
	//@Column MSGS_GRP_SEQ
	private int grpSeq;
	
	//The id of the host from the host table
	//@Column MSGS_HOSTID
	private String msgHost;
	
	//The id of the channel from the channels table
	//@Column MSGS_CHANNELID
	private String msgChannel;
	
	//The format of the channel type in which the host or gateway sends the message
	//@Column MSGS_MSGCHNLTYPE
	private String msgChnlType;
	
	//The message type of the message received from the source
	//@Column MSGS_SRC_MSGTYPE
	private String srcMsgType;
	
	//The sub type of the message received from the source
	//@Column MSGS_SRC_MSGSUBTYPE
	private String srcMsgSubType;
	
	//The message type of the message to be sent to destination
	//@Cloumn MSGS_DST_MSGTYPE
	private String dstMsgType;
	
	//The message sub type of the message to be sent to destination
	//Column MSGS_DST_SUBMSGTYPE
	private String dstMsgSubType;
	
	//The message status - current
	//@Column MSGS_MSGSTS
	private String msgStatus;
	
	//The message status -Previous
	//@Column MSGS_PREVMSGSTS
	private String msgPrevStatus;
	
	//The received time of the message
	//@Column MSGS_RECVDTIME
	private Timestamp receivedTime;
	
	//The last modified date and time of the message
	//@Column MSGS_LASTMODIFIEDTIME
	private Timestamp lastModTime;
	
	//Transaction reference of the payment probably given by bank host
	//@Column MSGS_PMTID_INSTRID
	private String txnReference;
	
	//Reference number given by the bank's customer
	//@Column MSGS_PMTID_ENDTOENDID
	private String custTxnReference;
	
	//Transaction reference of the payment probably given by bank host
	//@Column MSGS_PMTID_INSTGID FIXME get the correct name
	private String txRefMsgPay;
	
	//Reference number assigned by the clearing system of the country
	//@Column MSGS_PMTID_CLRSYSREF
	private String clrgSysReference;
	
	//Payment Priority set by sender
	//@Column MSGS_PMTTPLINF_INSTRPRTY
	private String sndrPymtPriority;
	
	//Clearing channel to be used for this payment
	//@Column MSGS_PMTTPLINF_CLRCHNL
	private String clrgChannel;
	
	//Service level code as in external service level code list and as agreed between the parties
	//@Column MSGS_PMTTPLINF_SVCLVL_CD
	private String svcLevelCode;
	
	//The properitary code for the service level agreed
	//@Column MSGS_PMTTPLINF_SVCLVL_PRTRY
	private String svcLevelPriority;
	
	//Local instrument code as in external local instrument code list
	//@Column MSGS_PMTTPLINF_LCLINSTRM_CD
	private String lclInstCode;
	
	//The properitary code for the local instrument code
	//@Column MSGS_PMTTPLINF_LCLINSTRM_PRTRY
	private String lclInstPriority;
	
	//Category purpose code as in external category purpose code list
	//@Column MSGS_PMTTPLINF_CTGYPURP_CD
	private String catgPurposeCode;
	
	//The properitary code for the categroy purpose
	//@Column MSGS_PMTTPLINF_CTGYPURP_PRTRY
	private String catgPurposePriority;
	
	//Currency of the interbank settlement
	//@Column MSGS_INTRBKSTTLMCCY
	private String msgCurrency;
	
	//Payment amount of the interbank settlement
	//@Column MSGS_INTRBKSTTLMAMT
	private double msgAmount;
	
	//The date on which the interbank settlement happens 
	//so that on this date the funds are no more available with sender.
	//@Column MSGS_INTRBKSTTLMDT
	private Timestamp msgValueDate;
	
	//Settlement priority set by the sender(values HIGH/NORM etc...)
	//@Column MSGS_INTRBKSTTLMPRTY
	private String sndrSttlmntPriority;
	
	//Date and time at which a payment has been debited at the transaction administrator
	//@Column MSGS_STTLMTMINDCTN_DBTDTTM
	private Timestamp drDateTime;
	
	//Date and time at which a payment has been credited at the transaction administrator
	//@Column MSGS_STTLMTMINDCTN_CDTDTTM
	private Timestamp crDateTime;
	
	//Time by which the amount of money must be credited, with confirmation, to the CLS Bank's 
	//account at the central bank.
	//@Column MSGS_STTLMTMREQ_CLSTM
	private Timestamp clsDateTime;
	
	//Time until when the payment may be settled
	//@Column MSGS_STTLMTMREQ_TILLTM
	private Timestamp sttlmntTillTime;
	
	//Time as from when the payment may be settled
	//@Column MSGS_STTLMTMREQ_FRTM
	private Timestamp sttlmntFromTime;
	
	//Time by when the payment must be settled to avoid rejection
	//@Column MSGS_STTLMTMREQ_RJCTTM
	private Timestamp sttlmntRejTime;
	
	//Point in time when the payment order from the initiating party meets the
	//processing conditions of the account servicing agent.
	//@Column MSGS_ACCPTNCDTTM
	private Timestamp pymntAcceptedTime;
	
	//Date used for the correction of the value date of a cash 
	//pool movement that has been posted with a different value date
	//@Column MSGS_POOLGADJSTMNTDT
	private Timestamp cashpoolAdjstmntTime;
	
	//Currency of the instructed amount
	//@Column MSGS_INSTDCCY
	private String instructedCurrency;
	
	//Amount of money to be moved between the debtor and creditor, before deduction of charges, expressed in
	//the currency as ordered by the initiating party.
	//@Column MSGS_INSTDAMT
	private double instructedAmount;
	
	//Exchange rate applied
	//@Column MSGS_XCHGRATE
	private double xchangeRate;
	
	//Charge bearer(values CRED, DEBT, SHAR and SLEV etc...)
	//@Column MSGS_CHRGBR
	private String chargeBearer;
	
	//Currency for charges
	//@Column MSGS_CHRGSINF_CCY
	private String chargeCurrency;
	
	//Charges amount
	//@Column MSGS_CHRGSINF_AMT
	private double chargeAmount;
	
	//The NGPH bank code for the charging party financial institution
	//@Column MSGS_CHRGSINF_PTY_BKCD
	private String chargingPartyBank;
	
	//The NGPH branch code of the charging party financial institution
	//@Column MSGS_CHRGSINF_PTY_BKBRNCD
	//private String chargingPartyBranch;
	
	//The NGPH bank code of the immediately prior instructing financial institution
	//@Column MSGS_PRVSINSTGAGT_BKCD
	private String prevInstructingBank;
	
	//The NGPH branch code of the immediately prior instructing financial institution
	//@Column MSGS_PRVSINSTGAGT_BKBRNCD
	//private String prevInstructingBranch;
	
	//The account ID as maintained in accounts master in NGPH for this immediately prior financial institution
	//@Column MSGS_PRVSINSTGAGT_ACCT
	private String prevInstructingAgentAcct;
	
	//The NGPH bank code for the instructing financial institution
	//@Column MSGS_INSTGAGT_BKCD
	private String senderBank;
	
	//The NGPH branch code of the instructing financial institution
	//@Column MSGS_INSTGAGT_BKBRNCD
	//private String senderBankBranch;
	
	//The NGPH bank code for the instructed financial institution
	//@Column MSGS_INSTDAGT_BKCD
	private String receiverBank;
	
	//The NGPH branch code of the instructed financial institution
	//@Column MSGS_INSTDAGT_BKBRNCD
	//private String receiverBankBranch;
	
	//The NGPH bank code for the intermediary agent 1's  financial institution
	//@Column MSGS_INTRMYAGT1_BKCD
	private String intermediary1Bank;
	
	//The NGPH branch code of the intermediary agent 1's  financial institution
	//@Column MSGS_INTRMYAGT1_BKBRNCD
	//private String intermediary1Branch;
	
	//The account ID as maintained in accounts master in NGPH for this intermediary financial institution
	//@Column MSGS_INTRMYAGT1_ACCT
	private String intermediary1AgentAcct;
	
	//The NGPH bank code for the intermediary agent 2's  financial institution
	//@Column MSGS_INTRMYAGT2_BKCD
	private String intermediary2Bank;
	
	//The NGPH branch code of the intermediary agent 2's  financial institution
	//@Column MSGS_INTRMYAGT2_BKBRNCD
	//private String intermediary2Branch;
	
	//The account ID as maintained in accounts master in NGPH for this intermediary financial institution
	//@Column MSGS_INTRMYAGT2_ACCT
	private String intermediary2AgentAcct;
	
	//The NGPH bank code for the intermediary agent 2's  financial institution
	//@Column MSGS_INTRMYAGT3_BKCD
	private String intermediary3Bank;
	
	//The NGPH branch code of the intermediary agent 2's  financial institution
	//@Column MSGS_INTRMYAGT3_BKBRNCD
	//private String intermediary3Branch;
	
	//The account ID as maintained in accounts master in NGPH for this intermediary financial institution
	//@Column MSGS_INTRMYAGT3_ACCT
	private String intermediary3AgentAcct;
	
	//Ultimate party that owes an amount of money to the (ultimate) creditor
	//@Column MSGS_ULTMTDBTR
	private String ultimateDebtor;
	
	//The NGPH Code of the party identifier as the initiating party
	//@Column MSGS_INITGPRTY
	private String initiatingParty;
	
	//The NGPH Code of the customer identifier as the debtor, the person who owes the money to the ultimate creditor. 
	//@Column MSGS_DBTR
	private String orderingCustomer;
	
	//The account id of the debtor customer
	//@Column MSGS_DBTRACCT
	private String orderingCustAccount;
	
	//Financial institution servicing an account for the debtor
	//@Column MSGS_DBTRAGT
	private String orderingInstitution;
	
	//Unambiguous identification of the account of the debtor agent at its servicing agent in the payment chain
	//@Column MSGS_DBTRAGTACCT
	private String orderingInstitutionAcct;
	
	//Financial institution servicing an account for the creditor
	//@Column MSGS_CDTRAGT
	private String accountWithInstitution;
	
	//Unambiguous identification of the account of the creditor agent at its servicing agent to which a credit entry will be made as a result of the payment transaction.
	//@Column MSGS_CDTRAGTACCT
	private String accountWithInstitutionAcct;
	
	//Party to which an amount of money is due
	//@Column MSGS_CDTR
	private String beneficiaryCustomer;
	
	//Unambiguous identification of the account of the creditor to which a credit entry will be posted as a result of the payment transaction.
	//@Column MSGS_CDTRACCT
	private String beneficiaryCustAcct;
	
	//Ultimate party to which an amount of money is due
	//@Column MSGS_ULTMTCDTR
	private String ultimateCreditor;
	
	//Coded information related to the processing of the payment instruction, provided by the initiating party, and intended for the creditor's agent.
	//@Column MSGS_INSTRFORCDTRAGT_CD
	private String instructionsForCrdtrAgtCode;
	
	//Further information complementing the coded instruction or instruction to the creditor's agent that is bilaterally agreed or specific to a user community.
	//@Column MSGS_INSTRFORCDTRAGT_INSTRINF
	private String instructionsForCrdtrAgtText;
	
	//Coded information related to the processing of the payment instruction, provided by the initiating party, and intended for the next agent in the payment chain.
	//@Column MSGS_INSTRFORNXTAGT_CD
	private String instructionsForNextAgtCode;
	
	//Further information complementing the coded instruction or instruction to the next agent that is bilaterally agreed or specific to a user community.
	//@Column MSGS_INSTRFORNXTAGT_INSTRINF
	private String instructionsForNextAgtText;
	
	//Underlying reason for the payment transaction, as published in an external purpose code list
	//@Column MSGS_PURP_CD
	private String msgPurposeCode;
	
	//Purpose, in a proprietary form
	//@Column MSGS_PURP_PRTRY
	private String msgPurposeText;
	
	//The identification of the regulatory reporting authority
	//@Column MSGS_RGLTRYRPTG_BKID
	private String regulatoryBankCode;
	
	//The currency of the information reported to the regulatory authority
	//@Column MSGS_RGLTRYRPTG_CCY
	private String regulatoryReportCurrency;
	
	//The amount that is reported to the regulatory authority
	//@Column MSGS_RGLTRYRPTG_AMT
	private double regulatoryReportAmount;
	
	//The information to the regulatory authority
	//@Column MSGS_RGLTRYRPTG_INF
	private String regulatoryInformation;
	
	//Unique identification, as assigned by the initiating party, to unambiguously identify the remittance information sent separately from the payment instruction, such as a remittance advice.
	//@Column MSGS_R_RMTID
	private String initiatorRemitReference;
	
	//Method used to deliver the remittance advice information
	//@Column MSGS_R_RMTLCTNMTD
	private String initiatorRemitAdviceMethod;
	
	//Electronic address to which an agent is to send the remittance information
	//@Column MSGS_R_RMTLCTNELCTRNCADR

	private String remitInfoEmail;
	
	//Name by which a party is known and is usually used to identify that identity
	//@Column MSGS_R_RMTLCTNPSTLADR_NM
	private String remitReceivingPartyName;
	
	//Postal address of a party.
	//@Column MSGS_R_RMTLCTNPSTLADR_ADR
	private String remitReceivingPartyAddress;
	
	//Related remittance information reference stored in remittance information table
	//@Column MSGS_R_RMTINF_REF
	private String relatedRemitInfo;
	
	//Remittance information stored in remittance information table
	//@Column MSGS_RMTINF_REF FIXME get the correct name
	private String remtInfoRef;
	
	//The return reference if any
	//@Column MSGS_RETURNREF
	private String msgReturnReference;
	
	//The identified customer account
	//@Column MSGS_IDTFD_CUSTAC
	private String custAccount;
	
	//The time of the batch for which this message was sent
	//@Column MSGS_BATCHTIME
	private Timestamp msgBatchTime;
	
	//The department code identified based on department rules. Will be set by entity control service
	//@Column MSGS_DEPT
	private String msgDept;
	
	//The branch that this message is intended for or sent by
	//@Column MSGS_BRANCH
	private String msgBranch;
	
	//The rules applied on this message
	//@Column MSGS_RULESAPPLIED
	private String msgRules;

	/**
	 * @return the msgRef
	 */
	public String getMsgRef() {
		return msgRef;
	}

	/**
	 * @param msgRef the msgRef to set
	 */
	public void setMsgRef(String msgRef) {
		this.msgRef = msgRef;
	}

	/**
	 * @return the grpMsgId
	 */
	public String getGrpMsgId() {
		return grpMsgId;
	}

	/**
	 * @param grpMsgId the grpMsgId to set
	 */
	public void setGrpMsgId(String grpMsgId) {
		this.grpMsgId = grpMsgId;
	}

	/**
	 * @return the grpSeq
	 */
	public int getGrpSeq() {
		return grpSeq;
	}

	/**
	 * @param grpSeq the grpSeq to set
	 */
	public void setGrpSeq(int grpSeq) {
		this.grpSeq = grpSeq;
	}

	/**
	 * @return the msgHost
	 */
	public String getMsgHost() {
		return msgHost;
	}

	/**
	 * @param msgHost the msgHost to set
	 */
	public void setMsgHost(String msgHost) {
		this.msgHost = msgHost;
	}

	/**
	 * @return the msgChannel
	 */
	public String getMsgChannel() {
		return msgChannel;
	}

	/**
	 * @param msgChannel the msgChannel to set
	 */
	public void setMsgChannel(String msgChannel) {
		this.msgChannel = msgChannel;
	}

	/**
	 * @return the msgChnlType
	 */
	public String getMsgChnlType() {
		return msgChnlType;
	}

	/**
	 * @param msgChnlType the msgChnlType to set
	 */
	public void setMsgChnlType(String msgChnlType) {
		this.msgChnlType = msgChnlType;
	}

	/**
	 * @return the srcMsgType
	 */
	public String getSrcMsgType() {
		return srcMsgType;
	}

	/**
	 * @param srcMsgType the srcMsgType to set
	 */
	public void setSrcMsgType(String srcMsgType) {
		this.srcMsgType = srcMsgType;
	}

	/**
	 * @return the srcMsgSubType
	 */
	public String getSrcMsgSubType() {
		return srcMsgSubType;
	}

	/**
	 * @param srcMsgSubType the srcMsgSubType to set
	 */
	public void setSrcMsgSubType(String srcMsgSubType) {
		this.srcMsgSubType = srcMsgSubType;
	}

	/**
	 * @return the dstMsgType
	 */
	public String getDstMsgType() {
		return dstMsgType;
	}

	/**
	 * @param dstMsgType the dstMsgType to set
	 */
	public void setDstMsgType(String dstMsgType) {
		this.dstMsgType = dstMsgType;
	}

	/**
	 * @return the dstMsgSubType
	 */
	public String getDstMsgSubType() {
		return dstMsgSubType;
	}

	/**
	 * @param dstMsgSubType the dstMsgSubType to set
	 */
	public void setDstMsgSubType(String dstMsgSubType) {
		this.dstMsgSubType = dstMsgSubType;
	}

	/**
	 * @return the msgStatus
	 */
	public String getMsgStatus() {
		return msgStatus;
	}

	/**
	 * @param msgStatus the msgStatus to set
	 */
	public void setMsgStatus(String msgStatus) {
		this.msgStatus = msgStatus;
	}

	/**
	 * @return the msgPrevStatus
	 */
	public String getMsgPrevStatus() {
		return msgPrevStatus;
	}

	/**
	 * @param msgPrevStatus the msgPrevStatus to set
	 */
	public void setMsgPrevStatus(String msgPrevStatus) {
		this.msgPrevStatus = msgPrevStatus;
	}

	/**
	 * @return the receivedTime
	 */
	public Timestamp getReceivedTime() {
		return receivedTime;
	}

	/**
	 * @param receivedTime the receivedTime to set
	 */
	public void setReceivedTime(Timestamp receivedTime) {
		this.receivedTime = receivedTime;
	}

	/**
	 * @return the lastModTime
	 */
	public Timestamp getLastModTime() {
		return lastModTime;
	}

	/**
	 * @param lastModTime the lastModTime to set
	 */
	public void setLastModTime(Timestamp lastModTime) {
		this.lastModTime = lastModTime;
	}

	/**
	 * @return the txnReference
	 */
	public String getTxnReference() {
		return txnReference;
	}

	/**
	 * @param txnReference the txnReference to set
	 */
	public void setTxnReference(String txnReference) {
		this.txnReference = txnReference;
	}

	/**
	 * @return the custTxnReference
	 */
	public String getCustTxnReference() {
		return custTxnReference;
	}

	/**
	 * @param custTxnReference the custTxnReference to set
	 */
	public void setCustTxnReference(String custTxnReference) {
		this.custTxnReference = custTxnReference;
	}

	/**
	 * @return the txRefMsgPay
	 */
	public String getTxRefMsgPay() {
		return txRefMsgPay;
	}

	/**
	 * @param txRefMsgPay the txRefMsgPay to set
	 */
	public void setTxRefMsgPay(String txRefMsgPay) {
		this.txRefMsgPay = txRefMsgPay;
	}

	/**
	 * @return the clrgSysReference
	 */
	public String getClrgSysReference() {
		return clrgSysReference;
	}

	/**
	 * @param clrgSysReference the clrgSysReference to set
	 */
	public void setClrgSysReference(String clrgSysReference) {
		this.clrgSysReference = clrgSysReference;
	}

	/**
	 * @return the sndrPymtPriority
	 */
	public String getSndrPymtPriority() {
		return sndrPymtPriority;
	}

	/**
	 * @param sndrPymtPriority the sndrPymtPriority to set
	 */
	public void setSndrPymtPriority(String sndrPymtPriority) {
		this.sndrPymtPriority = sndrPymtPriority;
	}

	/**
	 * @return the clrgChannel
	 */
	public String getClrgChannel() {
		return clrgChannel;
	}

	/**
	 * @param clrgChannel the clrgChannel to set
	 */
	public void setClrgChannel(String clrgChannel) {
		this.clrgChannel = clrgChannel;
	}

	/**
	 * @return the svcLevelCode
	 */
	public String getSvcLevelCode() {
		return svcLevelCode;
	}

	/**
	 * @param svcLevelCode the svcLevelCode to set
	 */
	public void setSvcLevelCode(String svcLevelCode) {
		this.svcLevelCode = svcLevelCode;
	}

	/**
	 * @return the svcLevelPriority
	 */
	public String getSvcLevelPriority() {
		return svcLevelPriority;
	}

	/**
	 * @param svcLevelPriority the svcLevelPriority to set
	 */
	public void setSvcLevelPriority(String svcLevelPriority) {
		this.svcLevelPriority = svcLevelPriority;
	}

	/**
	 * @return the lclInstCode
	 */
	public String getLclInstCode() {
		return lclInstCode;
	}

	/**
	 * @param lclInstCode the lclInstCode to set
	 */
	public void setLclInstCode(String lclInstCode) {
		this.lclInstCode = lclInstCode;
	}

	/**
	 * @return the lclInstPriority
	 */
	public String getLclInstPriority() {
		return lclInstPriority;
	}

	/**
	 * @param lclInstPriority the lclInstPriority to set
	 */
	public void setLclInstPriority(String lclInstPriority) {
		this.lclInstPriority = lclInstPriority;
	}

	/**
	 * @return the catgPurposeCode
	 */
	public String getCatgPurposeCode() {
		return catgPurposeCode;
	}

	/**
	 * @param catgPurposeCode the catgPurposeCode to set
	 */
	public void setCatgPurposeCode(String catgPurposeCode) {
		this.catgPurposeCode = catgPurposeCode;
	}

	/**
	 * @return the catgPurposePriority
	 */
	public String getCatgPurposePriority() {
		return catgPurposePriority;
	}

	/**
	 * @param catgPurposePriority the catgPurposePriority to set
	 */
	public void setCatgPurposePriority(String catgPurposePriority) {
		this.catgPurposePriority = catgPurposePriority;
	}

	/**
	 * @return the msgCurrency
	 */
	public String getMsgCurrency() {
		return msgCurrency;
	}

	/**
	 * @param msgCurrency the msgCurrency to set
	 */
	public void setMsgCurrency(String msgCurrency) {
		this.msgCurrency = msgCurrency;
	}

	/**
	 * @return the msgAmount
	 */
	public double getMsgAmount() {
		return msgAmount;
	}

	/**
	 * @param msgAmount the msgAmount to set
	 */
	public void setMsgAmount(double msgAmount) {
		this.msgAmount = msgAmount;
	}

	/**
	 * @return the msgValueDate
	 */
	public Timestamp getMsgValueDate() {
		return msgValueDate;
	}

	/**
	 * @param msgValueDate the msgValueDate to set
	 */
	public void setMsgValueDate(Timestamp msgValueDate) {
		this.msgValueDate = msgValueDate;
	}

	/**
	 * @return the sndrSttlmntPriority
	 */
	public String getSndrSttlmntPriority() {
		return sndrSttlmntPriority;
	}

	/**
	 * @param sndrSttlmntPriority the sndrSttlmntPriority to set
	 */
	public void setSndrSttlmntPriority(String sndrSttlmntPriority) {
		this.sndrSttlmntPriority = sndrSttlmntPriority;
	}

	/**
	 * @return the drDateTime
	 */
	public Timestamp getDrDateTime() {
		return drDateTime;
	}

	/**
	 * @param drDateTime the drDateTime to set
	 */
	public void setDrDateTime(Timestamp drDateTime) {
		this.drDateTime = drDateTime;
	}

	/**
	 * @return the crDateTime
	 */
	public Timestamp getCrDateTime() {
		return crDateTime;
	}

	/**
	 * @param crDateTime the crDateTime to set
	 */
	public void setCrDateTime(Timestamp crDateTime) {
		this.crDateTime = crDateTime;
	}

	/**
	 * @return the clsDateTime
	 */
	public Timestamp getClsDateTime() {
		return clsDateTime;
	}

	/**
	 * @param clsDateTime the clsDateTime to set
	 */
	public void setClsDateTime(Timestamp clsDateTime) {
		this.clsDateTime = clsDateTime;
	}

	/**
	 * @return the sttlmntTillTime
	 */
	public Timestamp getSttlmntTillTime() {
		return sttlmntTillTime;
	}

	/**
	 * @param sttlmntTillTime the sttlmntTillTime to set
	 */
	public void setSttlmntTillTime(Timestamp sttlmntTillTime) {
		this.sttlmntTillTime = sttlmntTillTime;
	}

	/**
	 * @return the sttlmntFromTime
	 */
	public Timestamp getSttlmntFromTime() {
		return sttlmntFromTime;
	}

	/**
	 * @param sttlmntFromTime the sttlmntFromTime to set
	 */
	public void setSttlmntFromTime(Timestamp sttlmntFromTime) {
		this.sttlmntFromTime = sttlmntFromTime;
	}

	/**
	 * @return the sttlmntRejTime
	 */
	public Timestamp getSttlmntRejTime() {
		return sttlmntRejTime;
	}

	/**
	 * @param sttlmntRejTime the sttlmntRejTime to set
	 */
	public void setSttlmntRejTime(Timestamp sttlmntRejTime) {
		this.sttlmntRejTime = sttlmntRejTime;
	}

	/**
	 * @return the pymntAcceptedTime
	 */
	public Timestamp getPymntAcceptedTime() {
		return pymntAcceptedTime;
	}

	/**
	 * @param pymntAcceptedTime the pymntAcceptedTime to set
	 */
	public void setPymntAcceptedTime(Timestamp pymntAcceptedTime) {
		this.pymntAcceptedTime = pymntAcceptedTime;
	}

	/**
	 * @return the cashpoolAdjstmntTime
	 */
	public Timestamp getCashpoolAdjstmntTime() {
		return cashpoolAdjstmntTime;
	}

	/**
	 * @param cashpoolAdjstmntTime the cashpoolAdjstmntTime to set
	 */
	public void setCashpoolAdjstmntTime(Timestamp cashpoolAdjstmntTime) {
		this.cashpoolAdjstmntTime = cashpoolAdjstmntTime;
	}

	/**
	 * @return the instructedCurrency
	 */
	public String getInstructedCurrency() {
		return instructedCurrency;
	}

	/**
	 * @param instructedCurrency the instructedCurrency to set
	 */
	public void setInstructedCurrency(String instructedCurrency) {
		this.instructedCurrency = instructedCurrency;
	}

	/**
	 * @return the instructedAmount
	 */
	public double getInstructedAmount() {
		return instructedAmount;
	}

	/**
	 * @param instructedAmount the instructedAmount to set
	 */
	public void setInstructedAmount(double instructedAmount) {
		this.instructedAmount = instructedAmount;
	}

	/**
	 * @return the xchangeRate
	 */
	public double getXchangeRate() {
		return xchangeRate;
	}

	/**
	 * @param xchangeRate the xchangeRate to set
	 */
	public void setXchangeRate(double xchangeRate) {
		this.xchangeRate = xchangeRate;
	}

	/**
	 * @return the chargeBearer
	 */
	public String getChargeBearer() {
		return chargeBearer;
	}

	/**
	 * @param chargeBearer the chargeBearer to set
	 */
	public void setChargeBearer(String chargeBearer) {
		this.chargeBearer = chargeBearer;
	}

	/**
	 * @return the chargeCurrency
	 */
	public String getChargeCurrency() {
		return chargeCurrency;
	}

	/**
	 * @param chargeCurrency the chargeCurrency to set
	 */
	public void setChargeCurrency(String chargeCurrency) {
		this.chargeCurrency = chargeCurrency;
	}

	/**
	 * @return the chargeAmount
	 */
	public double getChargeAmount() {
		return chargeAmount;
	}

	/**
	 * @param chargeAmount the chargeAmount to set
	 */
	public void setChargeAmount(double chargeAmount) {
		this.chargeAmount = chargeAmount;
	}

	/**
	 * @return the chargingPartyBank
	 */
	public String getChargingPartyBank() {
		return chargingPartyBank;
	}

	/**
	 * @param chargingPartyBank the chargingPartyBank to set
	 */
	public void setChargingPartyBank(String chargingPartyBank) {
		this.chargingPartyBank = chargingPartyBank;
	}

	/**
	 * @return the prevInstructingBank
	 */
	public String getPrevInstructingBank() {
		return prevInstructingBank;
	}

	/**
	 * @param prevInstructingBank the prevInstructingBank to set
	 */
	public void setPrevInstructingBank(String prevInstructingBank) {
		this.prevInstructingBank = prevInstructingBank;
	}

	/**
	 * @return the prevInstructingAgentAcct
	 */
	public String getPrevInstructingAgentAcct() {
		return prevInstructingAgentAcct;
	}

	/**
	 * @param prevInstructingAgentAcct the prevInstructingAgentAcct to set
	 */
	public void setPrevInstructingAgentAcct(String prevInstructingAgentAcct) {
		this.prevInstructingAgentAcct = prevInstructingAgentAcct;
	}

	/**
	 * @return the senderBank
	 */
	public String getSenderBank() {
		return senderBank;
	}

	/**
	 * @param senderBank the senderBank to set
	 */
	public void setSenderBank(String senderBank) {
		this.senderBank = senderBank;
	}

	/**
	 * @return the receiverBank
	 */
	public String getReceiverBank() {
		return receiverBank;
	}

	/**
	 * @param receiverBank the receiverBank to set
	 */
	public void setReceiverBank(String receiverBank) {
		this.receiverBank = receiverBank;
	}

	/**
	 * @return the intermediary1Bank
	 */
	public String getIntermediary1Bank() {
		return intermediary1Bank;
	}

	/**
	 * @param intermediary1Bank the intermediary1Bank to set
	 */
	public void setIntermediary1Bank(String intermediary1Bank) {
		this.intermediary1Bank = intermediary1Bank;
	}

	/**
	 * @return the intermediary1AgentAcct
	 */
	public String getIntermediary1AgentAcct() {
		return intermediary1AgentAcct;
	}

	/**
	 * @param intermediary1AgentAcct the intermediary1AgentAcct to set
	 */
	public void setIntermediary1AgentAcct(String intermediary1AgentAcct) {
		this.intermediary1AgentAcct = intermediary1AgentAcct;
	}

	/**
	 * @return the intermediary2Bank
	 */
	public String getIntermediary2Bank() {
		return intermediary2Bank;
	}

	/**
	 * @param intermediary2Bank the intermediary2Bank to set
	 */
	public void setIntermediary2Bank(String intermediary2Bank) {
		this.intermediary2Bank = intermediary2Bank;
	}

	/**
	 * @return the intermediary2AgentAcct
	 */
	public String getIntermediary2AgentAcct() {
		return intermediary2AgentAcct;
	}

	/**
	 * @param intermediary2AgentAcct the intermediary2AgentAcct to set
	 */
	public void setIntermediary2AgentAcct(String intermediary2AgentAcct) {
		this.intermediary2AgentAcct = intermediary2AgentAcct;
	}

	/**
	 * @return the intermediary3Bank
	 */
	public String getIntermediary3Bank() {
		return intermediary3Bank;
	}

	/**
	 * @param intermediary3Bank the intermediary3Bank to set
	 */
	public void setIntermediary3Bank(String intermediary3Bank) {
		this.intermediary3Bank = intermediary3Bank;
	}

	/**
	 * @return the intermediary3AgentAcct
	 */
	public String getIntermediary3AgentAcct() {
		return intermediary3AgentAcct;
	}

	/**
	 * @param intermediary3AgentAcct the intermediary3AgentAcct to set
	 */
	public void setIntermediary3AgentAcct(String intermediary3AgentAcct) {
		this.intermediary3AgentAcct = intermediary3AgentAcct;
	}

	/**
	 * @return the ultimateDebtor
	 */
	public String getUltimateDebtor() {
		return ultimateDebtor;
	}

	/**
	 * @param ultimateDebtor the ultimateDebtor to set
	 */
	public void setUltimateDebtor(String ultimateDebtor) {
		this.ultimateDebtor = ultimateDebtor;
	}

	/**
	 * @return the initiatingParty
	 */
	public String getInitiatingParty() {
		return initiatingParty;
	}

	/**
	 * @param initiatingParty the initiatingParty to set
	 */
	public void setInitiatingParty(String initiatingParty) {
		this.initiatingParty = initiatingParty;
	}

	/**
	 * @return the orderingCustomer
	 */
	public String getOrderingCustomer() {
		return orderingCustomer;
	}

	/**
	 * @param orderingCustomer the orderingCustomer to set
	 */
	public void setOrderingCustomer(String orderingCustomer) {
		this.orderingCustomer = orderingCustomer;
	}

	/**
	 * @return the orderingCustAccount
	 */
	public String getOrderingCustAccount() {
		return orderingCustAccount;
	}

	/**
	 * @param orderingCustAccount the orderingCustAccount to set
	 */
	public void setOrderingCustAccount(String orderingCustAccount) {
		this.orderingCustAccount = orderingCustAccount;
	}

	/**
	 * @return the orderingInstitution
	 */
	public String getOrderingInstitution() {
		return orderingInstitution;
	}

	/**
	 * @param orderingInstitution the orderingInstitution to set
	 */
	public void setOrderingInstitution(String orderingInstitution) {
		this.orderingInstitution = orderingInstitution;
	}

	/**
	 * @return the orderingInstitutionAcct
	 */
	public String getOrderingInstitutionAcct() {
		return orderingInstitutionAcct;
	}

	/**
	 * @param orderingInstitutionAcct the orderingInstitutionAcct to set
	 */
	public void setOrderingInstitutionAcct(String orderingInstitutionAcct) {
		this.orderingInstitutionAcct = orderingInstitutionAcct;
	}

	/**
	 * @return the accountWithInstitution
	 */
	public String getAccountWithInstitution() {
		return accountWithInstitution;
	}

	/**
	 * @param accountWithInstitution the accountWithInstitution to set
	 */
	public void setAccountWithInstitution(String accountWithInstitution) {
		this.accountWithInstitution = accountWithInstitution;
	}

	/**
	 * @return the accountWithInstitutionAcct
	 */
	public String getAccountWithInstitutionAcct() {
		return accountWithInstitutionAcct;
	}

	/**
	 * @param accountWithInstitutionAcct the accountWithInstitutionAcct to set
	 */
	public void setAccountWithInstitutionAcct(String accountWithInstitutionAcct) {
		this.accountWithInstitutionAcct = accountWithInstitutionAcct;
	}

	/**
	 * @return the beneficiaryCustomer
	 */
	public String getBeneficiaryCustomer() {
		return beneficiaryCustomer;
	}

	/**
	 * @param beneficiaryCustomer the beneficiaryCustomer to set
	 */
	public void setBeneficiaryCustomer(String beneficiaryCustomer) {
		this.beneficiaryCustomer = beneficiaryCustomer;
	}

	/**
	 * @return the beneficiaryCustAcct
	 */
	public String getBeneficiaryCustAcct() {
		return beneficiaryCustAcct;
	}

	/**
	 * @param beneficiaryCustAcct the beneficiaryCustAcct to set
	 */
	public void setBeneficiaryCustAcct(String beneficiaryCustAcct) {
		this.beneficiaryCustAcct = beneficiaryCustAcct;
	}

	/**
	 * @return the ultimateCreditor
	 */
	public String getUltimateCreditor() {
		return ultimateCreditor;
	}

	/**
	 * @param ultimateCreditor the ultimateCreditor to set
	 */
	public void setUltimateCreditor(String ultimateCreditor) {
		this.ultimateCreditor = ultimateCreditor;
	}

	/**
	 * @return the instructionsForCrdtrAgtCode
	 */
	public String getInstructionsForCrdtrAgtCode() {
		return instructionsForCrdtrAgtCode;
	}

	/**
	 * @param instructionsForCrdtrAgtCode the instructionsForCrdtrAgtCode to set
	 */
	public void setInstructionsForCrdtrAgtCode(String instructionsForCrdtrAgtCode) {
		this.instructionsForCrdtrAgtCode = instructionsForCrdtrAgtCode;
	}

	/**
	 * @return the instructionsForCrdtrAgtText
	 */
	public String getInstructionsForCrdtrAgtText() {
		return instructionsForCrdtrAgtText;
	}

	/**
	 * @param instructionsForCrdtrAgtText the instructionsForCrdtrAgtText to set
	 */
	public void setInstructionsForCrdtrAgtText(String instructionsForCrdtrAgtText) {
		this.instructionsForCrdtrAgtText = instructionsForCrdtrAgtText;
	}

	/**
	 * @return the instructionsForNextAgtCode
	 */
	public String getInstructionsForNextAgtCode() {
		return instructionsForNextAgtCode;
	}

	/**
	 * @param instructionsForNextAgtCode the instructionsForNextAgtCode to set
	 */
	public void setInstructionsForNextAgtCode(String instructionsForNextAgtCode) {
		this.instructionsForNextAgtCode = instructionsForNextAgtCode;
	}

	/**
	 * @return the instructionsForNextAgtText
	 */
	public String getInstructionsForNextAgtText() {
		return instructionsForNextAgtText;
	}

	/**
	 * @param instructionsForNextAgtText the instructionsForNextAgtText to set
	 */
	public void setInstructionsForNextAgtText(String instructionsForNextAgtText) {
		this.instructionsForNextAgtText = instructionsForNextAgtText;
	}

	/**
	 * @return the msgPurposeCode
	 */
	public String getMsgPurposeCode() {
		return msgPurposeCode;
	}

	/**
	 * @param msgPurposeCode the msgPurposeCode to set
	 */
	public void setMsgPurposeCode(String msgPurposeCode) {
		this.msgPurposeCode = msgPurposeCode;
	}

	/**
	 * @return the msgPurposeText
	 */
	public String getMsgPurposeText() {
		return msgPurposeText;
	}

	/**
	 * @param msgPurposeText the msgPurposeText to set
	 */
	public void setMsgPurposeText(String msgPurposeText) {
		this.msgPurposeText = msgPurposeText;
	}

	/**
	 * @return the regulatoryBankCode
	 */
	public String getRegulatoryBankCode() {
		return regulatoryBankCode;
	}

	/**
	 * @param regulatoryBankCode the regulatoryBankCode to set
	 */
	public void setRegulatoryBankCode(String regulatoryBankCode) {
		this.regulatoryBankCode = regulatoryBankCode;
	}

	/**
	 * @return the regulatoryReportCurrency
	 */
	public String getRegulatoryReportCurrency() {
		return regulatoryReportCurrency;
	}

	/**
	 * @param regulatoryReportCurrency the regulatoryReportCurrency to set
	 */
	public void setRegulatoryReportCurrency(String regulatoryReportCurrency) {
		this.regulatoryReportCurrency = regulatoryReportCurrency;
	}

	/**
	 * @return the regulatoryReportAmount
	 */
	public double getRegulatoryReportAmount() {
		return regulatoryReportAmount;
	}

	/**
	 * @param regulatoryReportAmount the regulatoryReportAmount to set
	 */
	public void setRegulatoryReportAmount(double regulatoryReportAmount) {
		this.regulatoryReportAmount = regulatoryReportAmount;
	}

	/**
	 * @return the regulatoryInformation
	 */
	public String getRegulatoryInformation() {
		return regulatoryInformation;
	}

	/**
	 * @param regulatoryInformation the regulatoryInformation to set
	 */
	public void setRegulatoryInformation(String regulatoryInformation) {
		this.regulatoryInformation = regulatoryInformation;
	}

	/**
	 * @return the initiatorRemitReference
	 */
	public String getInitiatorRemitReference() {
		return initiatorRemitReference;
	}

	/**
	 * @param initiatorRemitReference the initiatorRemitReference to set
	 */
	public void setInitiatorRemitReference(String initiatorRemitReference) {
		this.initiatorRemitReference = initiatorRemitReference;
	}

	/**
	 * @return the initiatorRemitAdviceMethod
	 */
	public String getInitiatorRemitAdviceMethod() {
		return initiatorRemitAdviceMethod;
	}

	/**
	 * @param initiatorRemitAdviceMethod the initiatorRemitAdviceMethod to set
	 */
	public void setInitiatorRemitAdviceMethod(String initiatorRemitAdviceMethod) {
		this.initiatorRemitAdviceMethod = initiatorRemitAdviceMethod;
	}

	/**
	 * @return the remitInfoEmail
	 */
	public String getRemitInfoEmail() {
		return remitInfoEmail;
	}

	/**
	 * @param remitInfoEmail the remitInfoEmail to set
	 */
	public void setRemitInfoEmail(String remitInfoEmail) {
		this.remitInfoEmail = remitInfoEmail;
	}

	/**
	 * @return the remitReceivingPartyName
	 */
	public String getRemitReceivingPartyName() {
		return remitReceivingPartyName;
	}

	/**
	 * @param remitReceivingPartyName the remitReceivingPartyName to set
	 */
	public void setRemitReceivingPartyName(String remitReceivingPartyName) {
		this.remitReceivingPartyName = remitReceivingPartyName;
	}

	/**
	 * @return the remitReceivingPartyAddress
	 */
	public String getRemitReceivingPartyAddress() {
		return remitReceivingPartyAddress;
	}

	/**
	 * @param remitReceivingPartyAddress the remitReceivingPartyAddress to set
	 */
	public void setRemitReceivingPartyAddress(String remitReceivingPartyAddress) {
		this.remitReceivingPartyAddress = remitReceivingPartyAddress;
	}

	/**
	 * @return the relatedRemitInfo
	 */
	public String getRelatedRemitInfo() {
		return relatedRemitInfo;
	}

	/**
	 * @param relatedRemitInfo the relatedRemitInfo to set
	 */
	public void setRelatedRemitInfo(String relatedRemitInfo) {
		this.relatedRemitInfo = relatedRemitInfo;
	}

	/**
	 * @return the remtInfoRef
	 */
	public String getRemtInfoRef() {
		return remtInfoRef;
	}

	/**
	 * @param remtInfoRef the remtInfoRef to set
	 */
	public void setRemtInfoRef(String remtInfoRef) {
		this.remtInfoRef = remtInfoRef;
	}

	/**
	 * @return the msgReturnReference
	 */
	public String getMsgReturnReference() {
		return msgReturnReference;
	}

	/**
	 * @param msgReturnReference the msgReturnReference to set
	 */
	public void setMsgReturnReference(String msgReturnReference) {
		this.msgReturnReference = msgReturnReference;
	}

	/**
	 * @return the custAccount
	 */
	public String getCustAccount() {
		return custAccount;
	}

	/**
	 * @param custAccount the custAccount to set
	 */
	public void setCustAccount(String custAccount) {
		this.custAccount = custAccount;
	}

	/**
	 * @return the msgBatchTime
	 */
	public Timestamp getMsgBatchTime() {
		return msgBatchTime;
	}

	/**
	 * @param msgBatchTime the msgBatchTime to set
	 */
	public void setMsgBatchTime(Timestamp msgBatchTime) {
		this.msgBatchTime = msgBatchTime;
	}

	/**
	 * @return the msgDept
	 */
	public String getMsgDept() {
		return msgDept;
	}

	/**
	 * @param msgDept the msgDept to set
	 */
	public void setMsgDept(String msgDept) {
		this.msgDept = msgDept;
	}

	/**
	 * @return the msgBranch
	 */
	public String getMsgBranch() {
		return msgBranch;
	}

	/**
	 * @param msgBranch the msgBranch to set
	 */
	public void setMsgBranch(String msgBranch) {
		this.msgBranch = msgBranch;
	}

	/**
	 * @return the msgRules
	 */
	public String getMsgRules() {
		return msgRules;
	}

	/**
	 * @param msgRules the msgRules to set
	 */
	public void setMsgRules(String msgRules) {
		this.msgRules = msgRules;
	}

}
